### ISSUE TITLE
Download Reference periode and figure out which variables are needed

### ISSUE THREAD

**Issue by tdiepenb** [annweitz/extreme-weather-db#3]
Download Reference periode (1961-1990 included) and figure out which variables we need for the Climatology for T2m

- Climatology for T2m from 1961-1990 (included)
   - Daily mean, min, max
       - 10th percentile from daily min
       - 95th percentile from daily max
       - 15 day running mean
       - for subest calculate 75 th, 80 th , 85 th, 90 th,, 95th percentiles to select one for upper tail percentile

**Comment by babypanda212** [comment]
We have decided not to include climatology in our analysis.
